### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by NicolasProy** [OpenVVC/OpenVVC#1]
Hi!

I have compiled OpenVVC recently and tried to use it but have a few issues with it . 
First of all, the "dectest" file used for decoding is located in the OpenVVC-master/build/examples, and cannot be found anywhere else, is this a compilation problem or is it supposed to be here?
Second, when I use the "make test" command, the command prompt shows that the test files located in "./CI/test_bitstreams/" are decoded and that the resulting .yuv files are located in the same directory but when I check there is no .yuv file in this directory.
Third, I tried to decode a .bin file given by the VTM software and a .bit file and the error "Segmentation fault (core dumped)" is diplayed, it seems that only .h266 can be decoded by OpenVVC, why is that?

Thanks in advance,
Nicolas.

**Comment by pcabarat** [comment]
Hi Nicolas!

I'll try to my best answer every question.

The location of "dectest" is right.
OpenVVC is supposed to be a library.
The "dectest" program is only supposed to be a short example program demonstrating how the library can be used or for debugging purposes.

The test target purpose is to help OpenVVC developers with non regression tests.
It decodes located in the ./CI/test_bistreams/ directory computes a md5 checksum on the output .yuv files and compares it to the expected md5 sums obtained on the .yuv files decoded from the reference software on the same bitstreams.
The generated .yuv files are then removed from the directory.

Regarding the "Segmentation fault" issue, this is pretty much expected but unwanted behavior at the current stage of OpenVVC development.
The file extension should not be an issue as long as the file only contains raw VVC video as specified in annex B of ITU-T H.266 Versatile Video Coding.
The issue is more likely related to unsupported VVC configuration.
OpenVVC does not offer full support of the VVC standard yet and still lacks proper error handling and reporting on unsupported tools and/or configuration.

We expect to release next week a new version supporting VTM default All Intra configuration before moving onto the support of missing inter tools/features on the following releases.

Pierre-Loup.

**Comment by NicolasProy** [comment]
Thanks a lot for your answer, it is very clear now!

Nicolas.
