### ISSUE TITLE
dectest does not exit

### ISSUE THREAD

**Issue by adamjw24** [OpenVVC/OpenVVC#5]
The dectest app/script does not exit when done. Ctrl-C does not help.

After inputting Ctrl-C into the terminal, I have to wait for around 30s/1min for the encoder to exit. I didn't try if it eventually exits on its own.

Ubuntu 20.04 LTS, default build options.

Best regards,
Adam

**Comment by gugautie** [comment]
Hello Adam,

Have you tried the test command provided in the README ?
 `./CI/checkMD5.sh ./CI/test_bitstreams/random_access ./examples/dectest http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/random_access/`
If not could run it ?

If the test command is working could you send us the bitstream used, in order to troubleshoot it?

Best Regards,

Guillaume

**Comment by adamjw24** [comment]
I think the problem was trying to use the dectest (and .lib directory) independently. If copying the whole examples directory, and using the full path to run (examples/dectest), it seems to work now.
